### ISSUE TITLE
"contact" and other short pages look a bit bland

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website2017#1]

**Comment by rphi** [comment]
Do we have a cache of photos around somewhere? I know we can steal some off Facebook, but also FB compresses them pretty massively so they look bad when stretched. Just thinking a (parallaxy?) full-width image could *potentially* look nice, although I'm not sure whether that would fit with the design... I think I still have the ones from Arthur's seat lady year around, where however is a different and far more difficult question. (Also not sure whether we got permission from people that we could use photos that may include them in for publicity which may be worth putting somewhere prior to this year's fresher's week events)

**Comment by qaisjp** [comment]
hmm, we have last year's photos lying somewhere on google photos somewhere.

[i've been experimenting...](https://imgur.com/a/ybZiS) (thankfully it doesn't look too shabby on mobile too!)

what do you think of this?

**Comment by rphi** [comment]
I was thinking of slightly lower height on the images, with them being full display width with some kind of overlay/inset shadow type thing? Maybe even a call to action button overlaid on the image. Although all of that may just be ott and naff. But definitely looks nice with the images (there aren't currently too many on the site which seems a shame)

**Comment by rphi** [comment]
Hows about something more like this?

![screen shot 2017-07-24 at 20 37 03](https://user-images.githubusercontent.com/8237136/28541164-e37bf2ae-70af-11e7-929f-b45dc72f0668.png)

**Comment by qaisjp** [comment]
Actually, what if we used a carousel? https://v4-alpha.getbootstrap.com/components/carousel/

that way it doesn't look arse on thin screens, and we can put in multiple images. we can experiment with doing a full width carousel

**Comment by neanias** [comment]
I’m not sure that’s really what we want just for ‘Find us on Fb/Tw/Insta/FuckKnows’.

**Comment by qaisjp** [comment]
@neanias what do you mean?

**Comment by neanias** [comment]
I don’t think the presentation fits with the content. I think it would fit better for the classic ‘look at these things we did’ or ‘enjoy these photos of a multicultural group of people smiling and laughing’.

**Comment by qaisjp** [comment]
I'm still slightly confused. I was imagining the existing contact page but with a carousel at the top with a bunch of interesting photos to flatten it out. Are you suggesting that the carousel would be out of place, and would be better elsewhere?

**Comment by neanias** [comment]
Sorry, my bad, I missed the beginning of the conversation. I thought you were proposing putting the 'find us on Fb/Tw/Insta' buttons in a carousel, not some phots!
