### ISSUE TITLE
Fix security alert

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website2017#109]
This is why we don't be proper and use Gemfiles

**Comment by neanias** [comment]
But we do use a Gemfile...?

**Comment by qaisjp** [comment]
s/don't/shouldn't ... _it was a bad joke okay_

**Comment by neanias** [comment]
I spend too much time dealing with people who don't know the virtues of dependency management and locking. I need to asume the worst sometimes.

**Comment by neanias** [comment]
Anyway, plz look at PR

**Comment by neanias** [comment]
Fixed in #110.
