### ISSUE TITLE
Build warning (Liquid) in team.md

### ISSUE THREAD

**Issue by rphi** [compsoc-edinburgh/website2017#23]
Anyone else seeing this?

```
Regenerating: [...]     Liquid Warning: Liquid syntax error (line 5): Expected dotdot but found pipe in "{{(site.data.committee | sort) | reverse }}" in [...]/compsoc-website/_pages/team.md
```

**Comment by qaisjp** [comment]
What does `jekyll --version` report?

**Comment by rphi** [comment]
`jekyll 3.5.1`? I installed with homebrew which maybe has confused things.

**Comment by qaisjp** [comment]
my server is on 3.5.1 as well, this is weird

**Comment by rphi** [comment]
It still builds fine, so it's not a major issue. Just makes the log look less nice.

**Comment by qaisjp** [comment]
hmm my server randomly started outputting this, but has now stopped doing it...

**Comment by qaisjp** [comment]
@rphi are you still getting this? my server has stopped saying it.

**Comment by qaisjp** [comment]
Closing this, feel free to reopen if it reappears.

**Comment by rphi** [comment]
Yep, it's dissapeared for me. :shrug:
