### ISSUE TITLE
add details about SIG: Web

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website2017#29]
see README.md in this repo for potential content

**Comment by rphi** [comment]
Would this be a new page or somehow integrated into the SIGs page?

**Comment by qaisjp** [comment]
new page, but it could be a separate website at `sigweb.comp-soc.com`. This issue just outlines there is little info about sigweb. Get the opinions @neanias and @hreeder — the two main sigweb guys.
