### ISSUE TITLE
"team" needs to look less bootstrappy

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website2017#3]

**Comment by rphi** [comment]
Can't say I'd agree with this tbh. However making the year navigation sticky/floating might be nice. Or maybe add some block colour to the headings but it is perfectly nice as it is.

**Comment by qaisjp** [comment]
https://github.com/compsoc-edinburgh/website2017/commit/302ab19ff5469915bdf0df3982bd4cd00fd952b4 should do
