### ISSUE TITLE
write "discord" blog post

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website2017#5]

**Comment by aptgetmoo** [comment]
@qaisjp when you say "blog post", what do you mean?
Just an article linked off the community page?

**Comment by qaisjp** [comment]
ah, thanks, i can mention this in the "welcome" blog post I'm writing.

A more detailed blog post can be written about the Discord bridge and how it works.

It's an actual blog tho, see comp-soc.com/blog

**Comment by aptgetmoo** [comment]
Righto, missed that somehow - thanks for the clarification 🎉
