### ISSUE TITLE
Migrate from v4-alpha to v4-beta

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website2017#57]
Why?

I don't know.

**Comment by rphi** [comment]
I'll take a look and see how much breaks, I get the feeling it should be near enough a drop-in upgrade?

**Comment by qaisjp** [comment]
Some things have been _removed_, and some of the flexbox class names have been changed.

**Comment by rphi** [comment]
Oh my this has broken many things... Still I'm on the case.

**Comment by rphi** [comment]
Current todo list:
- [x] Replace references to v4-alpha sources to v4-beta
- [x] Fix navbar collapse
- [x] Fix community page Better Informatics link and Twitter panes
- [ ] Fix slightly unusual nav alignment
- [ ] Fix calendar JS on events page (won't load anything for some reason)
- [ ] Buttons seem to be duplicated on blog posts
- [ ] Quotes look wrong on blog posts
- [ ] Team page layout has flipped (?) and the 'annual report' button is in the wrong place

I'm going to continue working on things but if anyone wants to try their hand (particularly whoever wrote the calendar thing) that could be handy.

**Comment by qaisjp** [comment]
Calendar JS won't load anything probably because the API key requires a valid referrer :)

It should work if you mess around with your hosts file!

**Comment by qaisjp** [comment]
I've fixed the team page layout. 

I think we can ignore the quotes styling as it looks like they've changed the styling outright.

([before](https://v4-alpha.getbootstrap.com/content/typography/#blockquotes), [after](https://getbootstrap.com/docs/4.0/content/typography/#blockquotes))
