### ISSUE TITLE
twitter profile images links broken

### ISSUE THREAD

**Issue by JMaio** [compsoc-edinburgh/website2017#74]
profile images link to static images that may be subject to change (and are currently invalid links for @hacktheburgh and @SIGINThq)

**Comment by qaisjp** [comment]
fixed in #75

**Comment by itv-canterlot** [comment]
The profile photos fetch isn't working on mobile:

![](https://i.imgur.com/LfAPhC6.jpg)

Looks like [twitter.com/*account_name_here*/profile_image?size=original](https://twitter.com/SIGINThq/profile_image?size=original) exists, but [mobile.twitter.com/*account_name_here*/profile_image?size=original](https://mobile.twitter.com/SIGINThq/profile_image?size=original) doesn't.

**Comment by JMaio** [comment]
😱

**Comment by rphi** [comment]
Or just saving the Twitter profile images to the repo and serving them from comp-soc.com? Yes they'd be static but there shouldn't be any more issues at least like this.
